"""
Configuration module for Antigravity system
"""

from .system_config import (
    SYSTEM_CONFIG,
    AGENTS_CONFIG,
    TECH_STACKS,
    QUALITY_STANDARDS,
    COMPLIANCE_REQUIREMENTS,
    FEATURE_ROADMAP,
    ENVIRONMENTS,
    MONITORING_CONFIG,
    SECURITY_CONFIG,
    PROJECT_TEMPLATES
)

__all__ = [
    'SYSTEM_CONFIG',
    'AGENTS_CONFIG',
    'TECH_STACKS',
    'QUALITY_STANDARDS',
    'COMPLIANCE_REQUIREMENTS',
    'FEATURE_ROADMAP',
    'ENVIRONMENTS',
    'MONITORING_CONFIG',
    'SECURITY_CONFIG',
    'PROJECT_TEMPLATES'
]
